name: Deploy on Hugging Spaces

on: 
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_hf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Hugging Face Hub
        run: pip install huggingface_hub
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: |
          huggingface-cli login --token $HF_TOKEN
          git remote add hf https://huggingface.co/spaces/sunman91/demo2
          git push hf main
