name: Deploy on Hugging Spaces

on: 
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Add remote
      env:
        HF: ${{ secrets.HF }}
      run: |
        git remote set-url origin1 https://sunman91:$HF@huggingface.co/spaces/sunman91/demo2
    - name: Push to hub
      run: |
        git push origin1 main --force
